export const assets_images = {

    // // for review rating;
    // 'review_rating01': require('./images/reviews/review_rating01.png'),
    // 'review_rating02': require('./images/reviews/review_rating02.png'),
    // 'review_rating03': require('./images/reviews/review_rating03.png'),
    // 'review_rating04': require('./images/reviews/review_rating04.png'),
    // 'review_rating05': require('./images/reviews/review_rating05.png'),
    // 'review_rating_select01': require('./images/reviews/review_rating_select01.png'),
    // 'review_rating_select02': require('./images/reviews/review_rating_select02.png'),
    // 'review_rating_select03': require('./images/reviews/review_rating_select03.png'),
    // 'review_rating_select04': require('./images/reviews/review_rating_select04.png'),
    // 'review_rating_select05': require('./images/reviews/review_rating_select05.png'),


    // "question_reply": require('./images/question_reply.png'),
    // "question_asked": require('./images/question_asked.png'),
    // "search_white": require('./images/search_light.png'),
    "search_dark": require('./images/search_dark.png'),
    // "search_grey": require('./images/search_grey.png'),
    // "arrow_right_dark": require('./images/arrow_right_dark.png'),
    // "arrow_right_light": require('./images/arrow_right_light.png'),
    // "arrow_right_grey": require('./images/arrow_right_grey.png'),
    // "home_light": require('./images/home_light.png'),
    "home_dark": require('./images/home_dark.png'),
    // "wishlist_light": require('./images/favorite_light.png'),
    // "wishlist_dark": require('./images/favorite_dark.png'),
    // "wishlist_red": require('./images/favorite_red.png'),

    // "cart_light": require('./images/cart_light.png'),
    // "cart_dark": require('./images/cart_dark.png'),
    // "profile_light": require('./images/profile_light.png'),
    "profile_dark": require('./images/profile_dark.png'),
    // "order_light": require('./images/order_light.png'),
    // "order_dark": require('./images/order_dark.png'),
    // "shipping_address_dark": require('./images/shipping_address_dark.png'),
    // "shipping_address_light": require('./images/shipping_address_light.png'),
    // "support_ticket_dark": require('./images/support_ticket_dark.png'),
    // "filter_grey": require('./images/filter_grey.png'),
    // "filter_light": require('./images/filter_light.png'),
    // "support_ticket_light": require('./images/support_ticket_light.png'),
    // "log_out_dark": require('./images/log_out_dark.png'),
    // "log_out_light": require('./images/log_out_light.png'),
    "info_dark": require('./images/info_dark.png'),
    // "info_light": require('./images/info_light.png'),
    // "download_dark": require('./images/download_dark.png'),
    // "download_grey": require('./images/download_grey.png'),
    // "close_grey": require('./images/close_grey.png'),
    // "close_dark": require('./images/close_dark.png'),
    // "close_light": require('./images/close_light.png'),
    // "sorting_dark": require('./images/sorting_dark.png'),
    // "sorting_grey": require('./images/sorting_grey.png'),
    // "sorting_light": require('./images/sorting_light.png'),
    "checkbox_round_checked": require('./images/checkbox_round_checked.png'),
    "checkbox_round": require('./images/checkbox_round.png'),
    // "youtube_rounded_red": require('./images/youtube_rounded_red.png'),
    // "like_stroke_grey": require('./images/like_stroke_grey.png'),
    // "like_full_fill_white": require('./images/like_full_fill_white.png'),

    "ratings_full_check_primary": require('./images/ratings_full_check_primary.png'),
    "ratings_full_empty": require('./images/ratings_full_empty.png'),

    "arrow_left_indicate_light": require('./images/arrow_left_indicate_light.png'),
    // "menu_navbar_light": require('./images/menu_navbar_light.png'),

    // "male_avatar": require('./images/male_avatar.png'),
    // "female_avatar": require('./images/female_avatar.png'),



    // "carts3d": require('./images/3d/carts3d.png'),
    // "delete3d": require('./images/3d/delete3d.png'),
    // "browser_history3d": require('./images/3d/browser_history3d.png'),
    // "email3d": require('./images/3d/email3d.png'),
    // "expenditure3d": require('./images/3d/expenditure3d.png'),
    // "location3d": require('./images/3d/location3d.png'),
    // "notifications3d": require('./images/3d/notifications3d.png'),
    // "orders3d": require('./images/3d/orders3d.png'),
    // "edit3d": require('./images/3d/edit3d.png'),
    // "password3d": require('./images/3d/password3d.png'),
    // "person_256_3d": require('./images/3d/person_256_3d.png'),
    // "person3d": require('./images/3d/person3d.png'),
    // "phone3d": require('./images/3d/phone3d.png'),
    // "settings3d": require('./images/3d/settings3d.png'),
    // "wishlists3d": require('./images/3d/wishlists3d.png'),
    // "shipping_address3d": require('./images/3d/shipping_address3d.png'),
    // "sign_out3d": require('./images/3d/sign_out3d.png'),
    // "language_change3d": require('./images/3d/language_change3d.png'),
    // "gender3d": require('./images/3d/gender3d.png'),
    // "block3d": require('./images/3d/block3d.png'),
    // "support_ticket3d": require('./images/3d/support_ticket3d.png'),
    // "addCart3d": require('./images/3d/addCart3d.png'),
    // "upload3d": require('./images/3d/upload3d.png'),

    // // Gif
    // "loading_gif": require('./images/loading.gif'),
    // "processing_gif": require('./images/processing.gif'),

    // // BG
    // "signin_bg": require('./images/bg/signin_bg.png'),
    // "empty_address3d": require('./images/bg/empty_address3d.png'),
    // "order_completed3d": require('./images/bg/order_completed3d.png'),
    // "empty_wishlist3d": require('./images/bg/empty_wishlist3d.png'),
    // "empty_carts3d": require('./images/bg/empty_carts3d.png'),
    // "empty_notification3d": require('./images/bg/empty_wishlist3d.png'),
    // "disappointed_emoji3d": require('./images/bg/disappointed_emoji3d.png'),
}